# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galois.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 828)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(410, 10, 821, 781))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.twig_Galios_Table = QtWidgets.QTableWidget(self.groupBox)
        self.twig_Galios_Table.setGeometry(QtCore.QRect(10, 20, 801, 701))
        self.twig_Galios_Table.setObjectName("twig_Galios_Table")
        self.twig_Galios_Table.setColumnCount(0)
        self.twig_Galios_Table.setRowCount(0)
        self.twig_Galios_Table.verticalHeader().setVisible(False)
        self.pb_ExportToExcel = QtWidgets.QPushButton(self.groupBox)
        self.pb_ExportToExcel.setGeometry(QtCore.QRect(590, 730, 221, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pb_ExportToExcel.setFont(font)
        self.pb_ExportToExcel.setObjectName("pb_ExportToExcel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 391, 771))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pb_ShowPolynom = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_ShowPolynom.setGeometry(QtCore.QRect(210, 26, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pb_ShowPolynom.setFont(font)
        self.pb_ShowPolynom.setObjectName("pb_ShowPolynom")
        self.lw_SelectPolynom = QtWidgets.QListWidget(self.groupBox_3)
        self.lw_SelectPolynom.setGeometry(QtCore.QRect(10, 110, 371, 611))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lw_SelectPolynom.setFont(font)
        self.lw_SelectPolynom.setObjectName("lw_SelectPolynom")
        self.pb_Create_Table = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_Create_Table.setGeometry(QtCore.QRect(260, 730, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pb_Create_Table.setFont(font)
        self.pb_Create_Table.setObjectName("pb_Create_Table")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setGeometry(QtCore.QRect(0, 60, 391, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.le_Exponent = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_Exponent.setGeometry(QtCore.QRect(160, 30, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.le_Exponent.setFont(font)
        self.le_Exponent.setObjectName("le_Exponent")
        self.label_MainPolynomial = QtWidgets.QLabel(self.groupBox_3)
        self.label_MainPolynomial.setGeometry(QtCore.QRect(10, 730, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_MainPolynomial.setFont(font)
        self.label_MainPolynomial.setObjectName("label_MainPolynomial")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Построение расширенного поля Галуа GF(2^n)"))
        self.pb_ExportToExcel.setText(_translate("MainWindow", "Экспортировать в Excel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Выбор показателя степени и неприводимого полинома"))
        self.label_4.setText(_translate("MainWindow", "Показатель степени:"))
        self.pb_ShowPolynom.setText(_translate("MainWindow", "Отобразить полиномы"))
        self.pb_Create_Table.setText(_translate("MainWindow", "Отобразить поле"))
        self.label_5.setText(_translate("MainWindow", "Выбор полинома:"))
        self.label_MainPolynomial.setText(_translate("MainWindow", "polynom"))

